#!/bin/bash

commandToRun="kubectl $@"

# If collector env var not set
# default to localhost:4318
if [ -z $KP_OTELCOL_ENDPOINT ]
then
  KP_OTELCOL_ENDPOINT=http://localhost:4318
fi

# If service name not set
# default to helm
if [ -z $KP_SERVICE_NAME ]
then
  KP_SERVICE_NAME=kubectl
fi

time_start=0
$commandToRun
time_end=$SECONDS

duration=$(( $time_end - $time_start ))

tracepusher -e $KP_OTELCOL_ENDPOINT -sen $KP_SERVICE_NAME -spn "$commandToRun" -dur $duration
